name: build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  - cron: "0 6 * * *"

env:
  # https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ['', 'spring4']
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Compile
      run: ./mvnw clean test-compile --no-transfer-progress
    - name: Test
      run: ./mvnw verify -P "${{ matrix.profile }}" --no-transfer-progress
    - name: Coverage
      if: github.event_name != 'pull_request'
      run: ./mvnw org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report --no-transfer-progress -D repoToken=${{ secrets.COVERALLS_TOKEN }}
